"""initial_users_and_messages

Revision ID: 4d14c896b16a
Revises: 
Create Date: 2026-03-01 21:35:46.596971
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d14c896b16a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('server_msg_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('client_msg_id', sa.String(length=64), nullable=False),
    sa.Column('sender_id', sa.String(length=64), nullable=False),
    sa.Column('receiver_id', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.SmallInteger(), nullable=False),
    sa.Column('content_type', sa.SmallInteger(), nullable=False),
    sa.Column('body', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('server_msg_id'),
    sa.UniqueConstraint('client_msg_id')
    )
    op.create_index('ix_msg_receiver_waterline', 'messages', ['receiver_id', 'server_msg_id'], unique=False)
    op.create_index('ix_msg_sender', 'messages', ['sender_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('nickname', sa.String(length=64), server_default='', nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_msg_sender', table_name='messages')
    op.drop_index('ix_msg_receiver_waterline', table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
